import ResearchRoomImage from '../images/salle-recherche.png'
import ModalWindow from './ModalWindow'
import { ImageMap } from '@qiuz/react-image-map'
import '../style/room.css'
import Form from './Form'

function ResearchRoom({ isOpen, setIsOpen, closeModal }) {
    const makeRemedy = () => {
        setIsOpen(true)
    }

    const remedy = [{ width: '9.529025191675794%', height: '31.25%', left: '19.600561336254106%', top: '25.9765625%' }]
    const pc = [
        {
            width: '5.115511551155116%',
            height: '7.058823529411764%',
            left: '51.60719175936759%',
            top: '43.23529411764705%'
        }
    ]

    return (
        <>
            <ImageMap className="usage-map" src={ResearchRoomImage} map={remedy} onMapClick={makeRemedy} />
            <h2 id="room-title">Salle de recherches</h2>
            {isOpen ? <ModalWindow content={<Form />} isOpen={isOpen} closeModal={closeModal} /> : ''}
        </>
    )
}

export default ResearchRoom

/*

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Untitled.png" usemap="#image-map">

<map name="image-map">
    <area target="_blank" alt="" title="" href="" coords="848,348,756,291" shape="rect">
</map>

*/
