import ResearchRoomImage from '../images/salle-recherche.png'
import { ImageMap } from '@qiuz/react-image-map'

function ResearchRoom() {

    const mapArea = [
        {
            width: '10.561056105610561%',
            height: '10.882352941176471%',
            left: '72.06923796398806%',
            top: '49.117647058823536%'
        }
    ]
    
    return (
        <>
            <ImageMap className="usage-map" src={ResearchRoomImage} map={mapArea} />
        </>
    )
}

export default ResearchRoom

/*

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Untitled.png" usemap="#image-map">

<map name="image-map">
    <area target="_blank" alt="" title="" href="" coords="848,348,756,291" shape="rect">
</map>

*/
