import Form from './Form'

function ResearchRoom() {
    return (
        <>
            <Form></Form>
        </>
    )
}

export default ResearchRoom


/*

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="Untitled.png" usemap="#image-map">

<map name="image-map">
    <area target="_blank" alt="" title="" href="" coords="848,348,756,291" shape="rect">
</map>

*/

